apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::683913585070:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::683913585070:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-4LVH68EA2H2E
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2022-01-30T10:38:43Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1309"
  uid: 963c0bce-9d21-4466-863c-b088ddee40a1
